[build]
buildCommand = "scripts/build.sh && pip install -r requirements.txt"

[deploy]
startCommand = "streamlit run src/python/main.py --server.port=$PORT --server.address=0.0.0.0"
restartPolicyType = "on_failure"
